CREATE TABLE TODO_SET
(
  ID IDENTITY NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE TASK
(
    ID IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TODO_SET_ID BIGINT REFERENCES TODO_SET(ID),
    COMPLETED BOOLEAN DEFAULT FALSE
);
